supabase/auth-js

example/package-lock.json
example/src/App.js
example/src/tailwind.output.css
src/GoTrueApi.ts
src/GoTrueClient.ts
src/index.ts
test/client.test.ts
test/provider.test.ts
test/subscriptions.test.ts

Renames types to be more consistent across all of our libraries
BREAKING CHANGE: Client() -> GoTrueClient()
BREAKING CHANGE: Api() -> GoTrueApi()
We have several libraries which use the convention `<TYPE>Client`. For example, `PostgrestClient` and `SupabaseClient`. This change make this library consistent and clearer

fix: renames types to be more consistent across all of our libraries

---

src/GoTrueClient.ts
src/lib/types.ts

r? @kiwicopple 
- Fix function return types.
- Add types for `onAuthStateChange` callback function

chore: Fix function types.

---

example/README.md
example/package-lock.json
example/src/App.js
src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/fetch.ts
src/lib/helpers.ts
test/client.test.ts
test/subscriptions.test.ts

- expose `GoTrueAPI` from `GotrueClient`
- Type errors as Error objects
- Fix `getParameterByName` to recognize hash `#`
- Remove hash from URL once session has been restored

feat: expose api from client

---

RELEASE.md
example/src/App.js
src/GoTrueApi.ts
src/GoTrueClient.ts

r? @kiwicopple @awalias 
In this release we added `client.api.sendMagicLinkEmail()` and updated `client.signIn()` to support magic link login by only providing email credentials without a password.
Update the example to say 'Send magic link' instead of 'Sign in' on the button when no password input is provided

feat: Add magic link api method and sign in.

---

package-lock.json
package.json
src/GoTrueClient.ts
src/lib/helpers.ts
test/__snapshots__/client.test.ts.snap
test/client.test.ts

- tsc error fix supabase/supabase#150
- add @types/node supabase/supabase#150

fix tsc output for types

---

src/lib/fetch.ts

As discussed in #11.
Fixes the 400 responses caused by React Native on iOS defaulting the Content-Type to `application/x-www-form-urlencoded`.

Set default Content-Type for POST/PUT requests

---

src/GoTrueApi.ts

Have tested successfully against a supabase instance with:
```javascript
let { GoTrueClient } = require("@supabase/gotrue-js");
const auth = new GoTrueClient({
url: "http://<ref>.supabase.co/auth/v1/",
headers: {
apikey:
"<SUPABASE_SERVICE_ROLE_KEY> or <SUPABASE_ANON_KEY>",
Authorization:
"Bearer <SUPABASE_SERVICE_ROLE_KEY>",
},
});
auth.api
.inviteUserByEmail("ant@supabase.io" )
.then(console.log)
.catch(console.error);
```

feat: adds inviteUserByEmail for api users

---

src/index.ts

feature: https://github.com/supabase/gotrue-js/issues/28
The library does not export types
Export the gotrue-js types so they can be used in upstream libraries.
This PR will be followed by a PR to the supabase-js library so that all necessary types (gotrue, supabase, realtime) are available in TypeScript projects.

feat: add export of types for downstream use

---

src/GoTrueClient.ts

Fixes #23 
For environments where localstorage is async (e.g. AsyncStorage on React Native), fire a `SIGNED_IN` `onAuthStateChange` event as soon as the session has been recovered from localStorage.
That way the following pattern should solve things across the board: https://github.com/thorwebdev/nextjs-subscription-payments/blob/main/components/UserContext.js#L13-L28
```js
useEffect(() => {
const session = supabase.auth.session();
setSession(session);
setUser(session?.user ?? null);
const { data: authListener } = supabase.auth.onAuthStateChange(
async (event, session) => {
setSession(session);
setUser(session?.user ?? null);
}
);
return () => {
authListener.unsubscribe();
};
// eslint-disable-next-line react-hooks/exhaustive-deps
}, []);
```

fix: Fire signed in event on recoverSession.

---

src/GoTrueClient.ts

Fixes #27 
- Automatically recover expired sessions on page load using the refresh token

fix: Automatically recover expired sessions.

---

.gitignore
src/GoTrueApi.ts
src/GoTrueClient.ts
test/subscriptions.test.ts

Corrects typos:
- docs of api.signInWithEmail
- changed field client.stateChangeEmmitters to client.stateChangeEmitters
- changed method client._handeEmailSignIn to client._handleEmailSignIn
- changed method client._handeProviderSignIn to client._handleProviderSignIn
- docs of client.onAuthStateChange
- comment in client._recoverSession
Added .vscode/ (VisualStudioCode) to the gitignore file.
There are some typos.
Said typos have been fixed.

correct typos

---

src/lib/constants.ts

Loading this SDK in a browser context that does not have `process.env` defined currently throws an error. This fixes it so it handles if `process` is `undefined`.

Don't error if process is undefined

---

src/GoTrueClient.ts
src/lib/types.ts

Closes #39 
To help with resetting a user’s password I’m proposing to add another `onAuthChange` event called `PASSWORD_RECOVERY`.
This will help folks detect that someone has clicked on a recovery link and show the appropriate dialog. And to help with the dialog, I’ve added a `Auth.UpdatePassword` component: https://github.com/supabase/ui/pull/57. 
r? @kiwicopple @ykdojo

fix: fire PASSWORD_RECOVERY auth event

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/types.ts
test/__snapshots__/provider.test.ts.snap
test/provider.test.ts

Allows a user to request scopes while signing up/in with an OAuth provider, and returns `provider_token` which allows access to the provider's API.
```
const { user, session, error } = await supabase.auth.signIn({
provider: 'github'
}, {
scopes: 'repo notifications'
})
```

Enable passing scopes to provider

---

src/GoTrueClient.ts

Fix GoTrueClient.update() to persist updated data to storage.
GoTrueClient.update() doesn't persist updated user data to storage. It's only update currentUser object in memory.
When users refresh the browser, user data will be reverted and out of sync. 
after updating user data, persist the new data to storage.
#49

fix: persist updated user data to storage

---

src/GoTrueClient.ts

Call function for refreshing tokens correctly, so the method does not lose access to correct this object.
Method _callRefreshToken is passed directly into the setTimeout function, which causes that the _callRefreshToken method is called with a global object as this. 
Method _callRefreshToken is now called inside of arrow function which, assures correct this value inside the method.
This bug caused problems in my Expo application, I'm not sure if this bugfix is relevant on the web.

fix: call token refreshing with arrow function

---

src/GoTrueClient.ts

- auto refresh token timer only triggers when there is an existed token on storage. When user login the first time, the jwt token will expire and not auto refresh.
- doesn't keep reference of refresh token timer to cancel when starting a new one
- multiple places update currentSession and currentUser
- use `_saveSession` to update currentSession and currentUser
- `_saveSession` will also trigger auto refresh token
- keep auto refresh token reference so that we can cancel it before starting a new one. One 1 will run at a time.
- code refactoring
#70 #61

fix: refresh access token

---

src/lib/cookies.ts

Fixes #81 
Cookie is sent as `Secure` when using a vhost in a local development environment
Recognise vhosts ending in `.local` and don't send a `Secure` cookie.
Potentially a better fix would be to have the user customise if the cookie should be secure or not.

fix: recognise .local vhost and send insecure cookie

---

src/GoTrueClient.ts
src/lib/types.ts
test/clientWithAutoConfirmEnabled.test.ts

This adds the minimum viable context to set the auth headers required for supabase-js:
https://github.com/supabase/supabase-js/blob/906a076c8942fe86765f0b9430be5b0ad076036a/src/SupabaseClient.ts#L172

Use in a node context

---

src/GoTrueClient.ts

Notifies subscribers when using `setSession`
I'm not sure if this is entirely correct behavior, since `setSession` could be used to refresh the session rather than initiate it, resulting in an extraneous `SIGN_IN` event. We could add an additional check if it seems appropriate.
This fixes an issue for me when manually signing in a user with a refresh_token. I want `SIGN_IN` to fire so my app redirects like a normal session change.

fix: notify subscribers when setting session

---

src/lib/polyfills.ts

Fixes Mobile Safari <= 12.0 support.
Library is not consumable on Mobile Safari <= 12.0 due to a bad polyfill for `globalThis`.
For my case (a Next.js page) this leads to the entire webpage being just a blank white screen:
As per the above screenshot, the failing (and corrected) behaviour can be verified from an iOS 12.1 Simulator.
If the current polyfill fails, fallback to a simple `self.globalThis = self` polyfill, which will be correct for any sane browser:
* https://caniuse.com/?search=self
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
* > On the web you can use window, self, or frames - but in Web Workers only self will work.
The original polyfill comes from https://mathiasbynens.be/notes/globalthis. However, that blog post makes few …

fix: globalThis polyfill for Mobile Safari <= 12.0

---

src/GoTrueApi.ts

Corrected the return type of `inviteUserByEmail`.
The `/invite` API returns a User object as per https://github.com/supabase/gotrue/blob/master/api/invite.go#L73
`inviteUserByEmail` returned promise result `data` property is typed as `{}`, rather than `User`.
`inviteUserByEmail` returned promise result `data` property is now typed as `User`, matching the data returned from the `/invite` API.

fix: /invite API (inviteUserByEmail) returns a User

---

src/lib/types.ts

New feature: typescript support for already-existing Twitter social sign in button
Get TS / ES lint errors and breaks builds in vercel when you use twitter profile in supabase-ui auth component, eg:
```
<Auth.UserContextProvider supabaseClient={supabase}>
{/* this is fine: <Auth providers={['github', 'google']} supabaseClient={supabase} /> */}
<Auth providers={['github', 'google', 'twitter']} supabaseClient={supabase} />
</Auth.UserContextProvider>
```
stuff is good

feat: allow twitter profile

---

src/lib/types.ts

• added missing 'apple' provider to type Provider as it's used by Supabase Auth component

fix: add Apple as Provider in types

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/types.ts
test/__snapshots__/clientWithAutoConfirmEnabled.test.ts.snap
test/clientWithAutoConfirmEnabled.test.ts

This allows one to call auth.signIn() with a refresh_token to login and retrieve a session. The upside is that this allows one to login on mobile using third party oauth flows on React Native.
On React Native third party auth flows cannot currently establish a session as the redirect flows are browser based (e.g. `getSessionFromUrl()`). In the issues below a solution of passing access_token & refresh token to `signIn()` was proposed and accepted.
https://github.com/supabase/supabase-js/issues/145
https://github.com/supabase/gotrue/issues/37
This allows one to call `signIn()` and get a fresh session using a refresh token. Internally it calls `refreshAccessToken()` which establishes a fresh session but returns the same signature as login with email & password.
```js
// overly simple example …
```

Allow signIn() with a refresh_token to enable third party auth on React Native

---

src/GoTrueApi.ts
test/__snapshots__/provider.test.ts.snap

Encodes query string parameter values.
supabase/supabase#1915: redirectTo works but cuts the "and" params "&param2=val2&param3=val3".
`&` and other special characters are encoded.
I considered using [balazsbotond/urlcat](https://github.com/balazsbotond/urlcat) for readability and concision.
E.g.:
```typescript
let urlParams: string[] = [`provider=${encodeURIComponent(provider)}`]
if (options?.redirectTo) {
urlParams.push(`redirect_to=${encodeURIComponent(options.redirectTo)}`)
}
if (options?.scopes) {
urlParams.push(`scopes=${encodeURIComponent(options.scopes)}`)
}
return `${this.url}/authorize?${urlParams.join('&')}`
```
Would become:
```typescript
options.provider = provider
return urlcat(this.url, '/authorize', options)
```
However, the increase in bundle size would probably not be …

fix: supabase/supabase#1915 encode query string parameter values

---

src/GoTrueClient.ts

Handles JWT expiry <= 60s correctly.
supabase/supabase-js#178: Refresh token doesn't update when JWT expiry is set to 60, constantly updates when JWT expiry is set to less than 60 since `expiresAt - timeNow - 60` is negative.
When JWT expiry is set to more than 60, current behavior remains to refresh 60s before expiry. When JWT expiry is set to 60 or less, new behavior is to refresh 0.5s before expiry.
0.5s is chosen to support JWT expiry of 1s, even though that should be an edge case. That should usually still be enough time to reach the server before expiry.

fix: supabase/supabase-js#178 handle JWT expiry <= 60s

---

src/GoTrueClient.ts

Bug fix
fixes #99
when `autoRefreshToken` is `true` (the default), the `signIn` method starts a timer that prevents the node event loop from exiting.
this PR preserves the defaults, while allowing the node process to immediately exit. this change should not functionally affect the previous behavior of the timer in long-running node processes.
in node, we can ensure that the timeout will not require the Node.js event loop to remain active by immediately calling [`unref`](https://nodejs.org/dist/latest-v14.x/docs/api/timers.html#timers_timeout_unref). `unref` should be used judiciously, but it seems to fit well here.
alternatives to consider instead of making this change:
- add docs guidance suggesting `autoRefreshToken: false` when appropriate in node environments
- change the …

fix: refreshTokenTimer blocks node event loop exit

---

src/lib/types.ts

Twitch was deployed as a provider but did not exist in the Provider type array

fix: added 'twitch' to Providers

---

example/expo/App.tsx
src/GoTrueClient.ts
src/lib/helpers.ts

Bug fix
in 3rd party iframes in the incognito mode accessing `localStorage` might throw:
> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document
Accessing `localStorage` has been made **lazy** (has been removed from the synchronous initialization path of the module to the constructor of one of the classes). This only helps when one provides `localStorage` through options (which will benefit me because I can do that to avoid that unsafe access). You could try to improve the situation for all users as well but you would have to figure out what would be the most appropriate solution for your use case.
I've also refactored the code related to `localStorage` a little bit:
1. I'm creating a custom type for what you are actually using …

Access localStorage lazily to avoid DOMExceptions in constrained envs when `localStorage` is provided using options

---

package-lock.json
package.json

fix #135 
```
[9:47:03 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.7
[9:47:03 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module 'semantic-release-plugin-update-version-in-files'
Require stack:
- /home/runner/work/gotrue-js/gotrue-js/noop.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at resolveFileName (/home/runner/.npm/_npx/1729/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
at resolveFrom (/home/runner/.npm/_npx/1729/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
at module.exports (/home/runner/.npm/_npx/1729/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
at loadPlugin …
```

fix: semantic release failed

---

src/GoTrueApi.ts
src/GoTrueClient.ts
test/apiWithAutoConfirmDisabled.test.ts
test/clientWithAutoConfirmDisabled.test.ts
test/clientWithAutoConfirmEnabled.test.ts

Lets you add metadata when signing up a user instead of having to sign up then update.
Adding arbitrary data to the auth.user table is only possible via the update call.
You can optionally pass in user_metadata in the options object to add the metadata upon signup.
This PR expands on the proof of concept provided by @johncomposed in #91

passthrough user metadata on sign up

---

src/GoTrueApi.ts

Updates [delete user](https://supabase.io/docs/reference/javascript/delete-user) documentation page to emphasize about the service key should be used only on the server side.
No mention of service key.
[Linked Issue](https://github.com/supabase/supabase/issues/3018)
The docs are updated to emphasize that the service key should only be used on the server side.

docs: updated deleteUser documentation about service key on server side

---

src/GoTrueClient.ts

docs update
Jsdocs params for `cookieOptions` is missing in the GoTrueClient construction options. [Please check here.](https://github.com/supabase/gotrue-js/blob/02c16c0fbdcb9e4c409304769ec29cb58efa2f45/src/GoTrueClient.ts#L66)
jsdocs params for `cookieOptions` is added to the constructor options `jsdocs params`.

feat: add cookie options to the GoTrueClient constructor options's jsdocs params

---

src/GoTrueApi.ts
src/GoTrueClient.ts

Type fix
The declared type is misleading and requires typecasting to use the `error.status`
The DX got improved as the declared type is more accurate
This is what gets thrown by all the API methods:
https://github.com/supabase/gotrue-js/blob/7f32c7a12b792a4e135e059bd06469a5a9e73592/src/lib/fetch.ts#L20-L23
There is still a small chance of an actual `Error` being thrown here, for example, if `_getRequestParams` throws:
https://github.com/supabase/gotrue-js/blob/7f32c7a12b792a4e135e059bd06469a5a9e73592/src/lib/fetch.ts#L47
However, if the implementation is correct and the user uses the API in an intended way (by providing correct information, of the correct types) then this shouldn't really happen. So I find it better to be pragmatic here and assume that no `Error` can happen here and it …

Fixed the declared error type for API responses

---

README.md
src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/fetch.ts

This PR adds the ability to provide a custom `fetch` implementation as an option - this is most useful for environments where `cross-fetch` is not supported, for instance Cloudflare Workers or Vercel Edge Functions.
This is related to https://github.com/supabase/supabase-js/issues/154, and I believe a similar option would need to be added to the other libraries using `cross-fetch` before being finally added to `supabase-js`.
At the moment, `cross-fetch` is always used in all environments.
There is a new option `fetch` that can be provided to override `cross-fetch` with an alternative library (or the native `fetch`):
```js
import { GoTrueClient } from '@supabase/gotrue-js'
const GOTRUE_URL = 'http://localhost:9999'
const auth = new GoTrueClient({ url: GOTRUE_URL, fetch: fetch })
``` …

feat: allow providing custom fetch implementation

---

src/GoTrueClient.ts
test/clientWithAutoConfirmEnabled.test.ts
test/clientWithSignupsDisabled.test.ts

In the GoTrueClient, signIn, signUp and verifyOTP includes `data` as part of the response.
This `data` attributed is deprecated in favor of the `session`.
While the documentation for each no longer refers to being able to use `data` (see: https://supabase.io/docs/reference/javascript/auth-signup), each auth method stil provided for it and also the tests used data instead of session.
* Removes data from returned Promise of signIn, signUp, and verfifyOTP
* Replaces data for session in tests
The code can still be a little confusing in these cases, see `verifyOTP`:
```ts
const { data, error } = await this.api.verifyMobileOTP(phone, token, options)
if (error) {
throw error
}
if (!data) {
throw 'An error occurred on token verification.'
}
let session: Session | null = null
let user: User | null …
```

fix: Removes deprecated data for session

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/types.ts

When upgrading to the latest supabase-js (and hence gotrue-js) sdks for RedwoodJS, ran into the case where:
Now the client returns GoTrueApi's `ApiError` can not just an `Error`.
But, it didn't see that `ApiError` was exported to allow a change in all the auth methods from, for example:
```ts
login(options: {
email?: string | undefined
password?: string | undefined
phone?: string | undefined
provider?: Provider
refreshToken?: string
redirectTo?: string
scopes?: string
}): Promise<{
session: Session | null
user: User | null
provider?: Provider
url?: string | null
error: Error | null
}>
```
To use ` error: ApiError | null`
To match:
```
async signIn(
{ email, phone, password, refreshToken, provider }: UserCredentials,
options: {
redirectTo?: string
scopes?: string
} = {}
): Promise<{ …
```

fix: exports ApiError interface so can be used by third-party implementations

---

src/lib/types.ts

* Gotrue now returns a list of identities associated to a user in the user obj
* Added a `UserIdentity` interface and an `identities` field in User which is an array of `UserIdentity`

add typescript mapping for identities type

---

.github/workflows/ci.yml

As discussed with @kiwicopple we are removing Codecov from GoTrue-js to fix build

Remove code coverage from CI

---

src/lib/types.ts

Added support for using the Keycloak provider.
Support for Keycloak has been added in gotrue  https://github.com/supabase/gotrue/pull/371

Added keycloak provider type

---

src/lib/types.ts

* `createUser` and `updateUser` should allow passing the `phone` field as an argument

fix: add phone field to user attr

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueApi.test.ts

@kangmingtay I've refactored the types and simplified the api and client a bit. 
With the types like this, `type` is optional when providing `phone` but is required when providing `email` 👍

chore: refactor

---

src/lib/types.ts

Add WorkOS provider type to complement https://github.com/supabase/gotrue/pull/402 let's leave this here for now till we upgrade the GoTrue versions though.
no workos provider
workos provider added

Add WorkOS Provider type

---

src/GoTrueApi.ts

Bug fix
The `shouldCreateUser` flag was added in #199, but passing `{ shouldCreateUser: false }` into the options of `signIn` still creates the user because this ternary will always return `true`:
```js
const shouldCreateUser = options.shouldCreateUser ? options.shouldCreateUser : true
```
With this change the `shouldCreateUser` can be set to `false` and the user will not be created, but it is still defaulted to `true` if no value (`undefined` or `null`) is passed.
Related to: https://github.com/supabase/supabase/issues/1176

fix: properly default shouldCreateUser flag

---

src/GoTrueClient.ts

* setAuth should set the user in the session to whatever it was originally
* Address #243

fix: setAuth should not set user to null

---

src/lib/types.ts

* adds the `phone_change` otp type to the verify params

fix: add phone_change otp type

---

src/GoTrueClient.ts

Bug fix
Manually setting auth via `setAuth` does not notify any subscribers.
Manually setting auth via `setAuth` will notify all subscribers with event `TOKEN_REFRESHED`.
- See comment: https://github.com/supabase/supabase/issues/6290#issuecomment-1101831005

fix: notify all subscribers when calling setAuth

---

src/GoTrueClient.ts
src/lib/helpers.ts
test/GoTrueClient.test.ts

This is a proof of concept for a new async `getSession()` method. This allows users to get a valid session (not expired) as opposed to the synchronous `session()` method, which may return an expired session.
I know we're planning to discuss this further, but since I already had most of the code, I thought I'd throw something together quickly. It will hopefully make our discussion clearer if we have something to look at!
Once `gotrue-js` has a method like this (or similar) it will allow `supabase-js` to work something like:
```javascript
async function getAccessToken() {
const {session} = await auth.getSession()
return session?.access_token ?? null
}
const postgrestClient = new PostgrestClient({ getAccessToken, ... })
```
Then whenever `postgrestClient` is about to send a query, it can …

feat: added async getSession/getUser method

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

Bug fix
When the session is expired the new `getSession()` handler does not refresh it as `_recoverSession()` does not set `this.currentSession` if it has expired, so `getSession()` thinks the user is logged out.
`getSession()` reads from local storage (or in-memory storage) on every call, rather than relying on `this.currentSession`.
This also sets us up for the future, when we will be able to remove all the cross tab synchronisation logic.
This PR also deprecates a bunch of stuff, most notably `setAuth()`. As we're moving away from `this.currentSession`, `setAuth()` will not be needed to synchronise sessions across gotrue instances, as it can now be done via storage.

fix: getSession() read from localStorage every time

---

src/GoTrueClient.ts

Bug fix
`_persistSession()` makes a new object in `localStorage` for some reason so when reading it back out in `getSession()` needs to pull out the `currentSession` field.
Pulls out the `currentSession` field from the `persistedSession`

fix: destructure currentSession from persistedSession

---

package-lock.json
package.json
src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/errors.ts
src/lib/fetch.ts
src/lib/helpers.ts
src/lib/types.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

This PR refactors the return types for the `gotrue-js` client to match the pattern used by `storage-js`.
See: https://github.com/supabase/storage-js/pull/60
> There are some type errors, and functions return everything with | null, making it difficult for end-users to work with.
> Gotrue-js types are hard to work with and would benefit from union types everywhere. See what we’ve done in storage-js for inspiration 
See: https://github.com/supabase/storage-js/pull/60
* Functions now return type unions, which are more correct and "easier to work with".
* Updates tests
* Adds new error types
* Updates cross-fetch version to match storage
Tests pass.
```terminal
gotrue-js dt-error-types % npm run test:suite
> @supabase/gotrue-js@0.2.0 test:suite
> jest --runInBand
PASS …
```

feature): [gotrue-js] Refactor return and error types

---

src/GoTrueClient.ts

Bug fix for docs. `signOut()` docs currently seem to indicate that an access token is deleted on the server upon this function being called, but this isn't the case. Instead all refresh tokens are all revoked instead and access tokens will stay alive until they expire.
There is some discussion of changing this behavior in https://github.com/supabase/gotrue/issues/248, but the current behavior of `signOut()` is to just revoke all refresh tokens.
Before allowing this change through, can someone who is more familiar with the supabase source confirm that I am not totally wrong here. I believe I am right because the supabase GoTrue docs say that `/logout` only revokes refresh tokens (https://github.com/supabase/gotrue#post-logout), and the auth.api.SignOut() just seems to call this endpoint …

Docs don't reflect auth.api.SignOut behavior

---

infra/docker-compose.yml
package.json

Should resolve #188. With the new version of the `supabase/postgres` image, there would be the need to explicitly specify the `postgresql.conf` location to `/etc/postgresql/postgresql.conf`.

bump docker supabase/postgres to 14.1.0

---

.github/workflows/ci.yml
test/GoTrueApi.test.ts

Bumps CI to node 14 to mirror supabase-js. 
Also removes the test which validates that user cannot send a recovery email if a user doesn't exist because the changes in [this GoTrue PR](https://github.com/supabase/gotrue/pull/534) make the test no longer relevant.

Bump CI to node 14

---

src/GoTrueClient.ts
test/GoTrueApi.test.ts

Changes  the console log on error in getting session from URL from error -> to warn in order to fix  #240 . Seems more a DX thing so looping in Thor and Silentworks.

Possible change of error message when getting session fails

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/cookies.ts
src/lib/errors.ts
src/lib/types.ts

* Use a custom error class that extends `AuthError` instead of throwing a generic error

fix: add custom error classes

---

src/GoTrueApi.ts
src/GoTrueClient.ts

* Remove unnecessary events emitted 
* Remove multi-tab stuff because `getSession()` will always ensure that a valid session is returned or no session at all

fix: remove unnecessary events and multi-tab

---

src/GoTrueApi.ts

* Added support for generating email change links in (https://github.com/supabase/gotrue/pull/560)

fix: add email change types to generateLink

---

src/GoTrueClient.ts
src/lib/helpers.ts

The `_recoverSession` is now redundant as we read the session from `localStorage` every time.
@kangmingtay it also looks like we're duplicating the refresh timer logic in `_recoverAndRefresh` and `_saveSession`. I think we can pull this out into another method and then call it as needed. What do you think?

fix: remove _recoverSession

---

src/GoTrueClient.ts
src/lib/helpers.ts

Currently, the item in `localStorage` is stored with a surrounding object with a duplicated `expiresAt` timestamp.
This removes the surrounding object and stores the session directly. It also adds a check to ensure the item in `localStorage` is a valid session.

fix: cleanup localStorage session format

---

src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueClient.test.ts

Bug fix
Currently `refreshingDeferred` does not get resolved/rejected upon error. Also the deferred does not get reset to null during an error. See #334 
The deferred gets resolved upon AuthError and rejected upon other errors, and finally reset to null. Like this the deferred Promise behaves like the Promise returned by `_callRefreshToken` itself.
Closes #334

fix: resolve & reset deferred upon refresh error

---

src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

* Common methods should always return an object with `{ data: {...}, error: ... }`

feat: return types should always contain `data`

---

src/index.ts

Bug fix
Errors are not currently exported by the library.
Errors are exported to match the other libraries, for example `storage-js`: https://github.com/supabase/storage-js/blob/next/src/index.ts#L3

fix: export errors

---

package-lock.json
package.json
src/GoTrueClient.ts
src/lib/constants.ts
src/lib/errors.ts
src/lib/fetch.ts
test/fetch.test.ts

Bug fix
1. Since #301 the error `NETWORK_FAILURE.ERROR_MESSAGE` is not thrown anymore, without this message failed refresh request are not retryed anymore:
https://github.com/supabase/gotrue-js/blob/67a6575102be9c50763ff5d06fd2ee44b18a69f3/src/GoTrueClient.ts#L870-L877
2. When the server/cloudflare proxy sends a body with no or invalid json, the error handling throws an exception (see #289) and does not reject the promise.
3. 5xx server responses could be retryed as well (eg. cloudflares `524: A timeout occurred`)  
Resolves: #333
Related to: #289 
This PR introduces a new error `AuthRetryableFetchError` Exponential backoff will now retry if this error is returned. 
`handleError` will reject with `AuthRetryableFetchError` when  
- when fetch throws an error (behaviour as it was pre #301) …

Fix retry token refresh upon network failure and retry refresh upon 5xx errors

---

src/GoTrueApi.ts
src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

* Return `{ data, error }` for more methods like `getUser` and `updateUser` 
* Differentiate `auth.getUser` and `auth.api.getUser` by renaming the former to `auth.getUserFromSession` 
* Remove `verifyMobileOTP`

fix: refactor return types

---

src/GoTrueAdminApi.ts
src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

* `signInWithPassword` was not sending a 'sign-in' event
*  added sign-in event after a successful response
* `signInWithOAuth` ran into issues getting session from url because it was using `getUser()` which depended on an existing session to be set
* fixed by allowing getUser to take in an optional access token jwt  
* `getSession` should also return { data, error }
*  Nit: Lowercase OTP to Otp

feat: update signIn methods, getUser and getSession

---

src/GoTrueClient.ts
src/lib/types.ts

With this PR errors from `getUrlFromSession` are resolved in the `initialized` Promise. A consumer of the library can access the promise by calling `await client.initialize()` to access those errors.
Also it handles a callbackUrl the same way as a `verifyOtp`, `signUp`, `signInWith*` and removes an existing session from storage before continuing.

fix: don't throw errors in constructor

---

src/GoTrueClient.ts
src/lib/errors.ts
src/lib/types.ts

This builds up on #393 and improves it by distinguishing between errors originating from mal formed callback urls and real errors (eg. `error_decription` in url, error during `getUser()`).
When a malformed callback url is detected the error is ignored, and the initialization continues with `_recoverAndRefresh`
Also i removed `multiTab` from options, as this setting is not used anymore.

Distinguish between various callback url errors and return errors

---

src/GoTrueClient.ts
src/lib/errors.ts
src/lib/types.ts
test/GoTrueClient.test.ts

Bug fix
`_getSessionFromUrl()` is not waited for in `getSession()`, leading to the session either coming from the URL or localStorage, depending on which one returns quicker. This is indeterministic behaviour.
`getSession()` waits for `_getSessionFromUrl()`, meaning we always preference the session in the URL over localStorage.

fix: wait for _getSessionFromUrl()

---

src/GoTrueAdminApi.ts
src/GoTrueClient.ts
src/lib/fetch.ts
src/lib/helpers.ts
src/lib/local-storage.ts
src/lib/types.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

Bug fix
If you provide a custom storage adapter server side, it acts as a no-op as `gotrue-js` only calls storage implementations in the browser.
Storage is now always called if `persistSession` is `true`.
Cookie storage is now a viable option to use server side.

fix: move isBrowser localStorage check + other small fixes

---

src/lib/fetch.ts
src/lib/helpers.ts
test/fetch.test.ts

Bug fix
If a custom fetch implementation does not return a Response that is a instance of native fetch Response or a cross-fetch Response the `instanceof` check in the error handler fails.
The fetch responses are checked with a utility method
See [discussion in discord](https://discord.com/channels/839993398554656828/1011280048495542402)

fix: handle custom fetch error responses

---

src/GoTrueClient.ts
src/lib/types.ts

- adds `provider_refresh_token` to Session object.
- closes  #[131](https://github.com/supabase/gotrue-js/issues/131)

feat: add provider refresh token to session

---

src/lib/fetch.ts

Resolves issue #205 
supabase/gotrue:v2.16.3 does not permit requests with content-type `text/plain` and is therefore replaced with `application/json`

fix: send `application/json` in Content-Type header

---

src/GoTrueClient.ts

* `_startAutoRefreshToken` used to take in the current session which might go stale by the time the `setTImeout` callback is invoked
* Change `_startAutoRefreshToken` to always get the current session from storage / memory instead of relying on the `session` passed in 
* Fixes #454, #442, #444
* Tested with the following scenarios:
* `JWT_EXPIRY`: 30s, `REUSE_INTERVAL`: 10s, 5 tabs opened (firefox) 
* `JWT_EXPIRY`: 20s, `REUSE_INTERVAL`: 5s, 5 tabs opened (firefox)

fix: refresh token sync across multiple tabs

---

src/GoTrueClient.ts

* Fixes this [issue](https://github.com/supabase/gotrue-js/issues/450#issuecomment-1261628057) where setting the `Authorization` header when the client is created doesn't get used properly in `getUser` 
* The problem was due to the jwt being overridden in the `Authorization` header in the `_request` function (https://github.com/supabase/gotrue-js/blob/rc/src/lib/fetch.ts#L84-L87)

fix: getUser should default to authorization header

---

src/lib/types.ts

By using named types for `app_metadata` and `user_metadata` developers can use [TypeScript declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to enforce some form of type checking on these fields.
See: #241.
(Same as #464 but for next branch.)

refactor: use named metadata types on User (next)

---

src/lib/types.ts

By using named types for `app_metadata` and `user_metadata` developers can use [TypeScript declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to enforce some form of type checking on these fields.
See: #241.

refactor: use named metadata types on `User`

---

src/GoTrueClient.ts
src/lib/helpers.ts
test/GoTrueClient.test.ts
tsconfig.json

* Fixes `setSession` to make it safe to use in a server-side or SSR context
* `setSession` should take in an `access token` and `refresh token` and only perform a refresh if the `access_token` is expired. We derive the expiry from the `exp` claim in the `access_token`.  
* This is a breaking change because `setSession` now takes in an object.
* References #445 but made some changes to make it compatible for v2

feat: update setSession

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

Adds support for calling `setSession()` in a server-side rendering context. When used in SSR, the access and refresh tokens are typically sent from the browser to the server. Both of them represent the user's session. 
Users can thus call:
```typescript
await client.setSession({ 
access_token: req.cookies['my-access-token'], 
refresh_token: req.cookies['my-refresh-token'] 
})
```
To correctly extract the session information from the two cookies. The client can then be used to call other APIs and automatic refresh token management will take place.

feat: add `setSession` support for a SSR context

---

src/GoTrueClient.ts
src/lib/types.ts

* Return empty array instead of null for `currentAuthenticationMethods` field if session is null

refactor: getAuthenticatorAssuranceLevel method

---

src/GoTrueClient.ts

* `listFactors` should not read the factors from the JWT since it could be stale, it should always make a request to the /user endpoint to get the user and return the factors

fix: listFactors should use getUser

---

src/GoTrueClient.ts
src/lib/types.ts

`data` options were forgotten for some sign in methods.

fix: add forgotten `data` option for sign ins

---

src/GoTrueAdminApi.ts

fix #514 by removing the xform(transform) applied to the result of querying the `listFactors` and `deleteFactors` end points. This would mean that the response would be returned without any transformation applied to it

fix: remove xform on admin mfa methods

---

src/GoTrueClient.ts

It's sending `captchaToken` to GoTrue which needs to be snake case. Ouch.

fix: use `captcha_token` in `verifyOtp`

---

src/GoTrueClient.ts

Reverts supabase/gotrue-js#482 because #529 is causing a larger scale issue.

fix: revert "fix: respect `EXPIRY_MARGIN` on `getSession`"

---

src/GoTrueClient.ts
src/lib/fetch.ts
src/lib/helpers.ts
src/lib/types.ts

Adds a new `signInWithSSO` method as `@experimental` with which you can initiate Single Sign-On logic.

feat: add `signInWithSSO` method as `@experimental`

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

@kangmingtay, bit of a critical here. Completely my fault.
Fixes a critical issue with `setSession()`. With the errant code, as part of #536, if a token hasn't expired, the session is returned but never gets saved. I removed a line when consolidating, but it should've been moved up instead. I completely missed this, and I apologize.
Thanks to someone else for finding this! https://github.com/supabase/gotrue-js/issues/539#issuecomment-1334692479
Also tweaks the existing setSession test, to ensure the method is saving the session. This would've caught my coding error.

fix: setSession is in broken state after v2.4.0

---

src/lib/helpers.ts

This change fixes incorrect behavior of the `isBrowser()` function and relative functionality.
Currently, the `isBrowser()` function returns `true` in React Native environment on mobile devices. That is obviously wrong. 
Relevant issues: #495 and https://github.com/supabase/supabase/issues/3790
After the fix, the `isBrowser()` function will return `false` when running in React Native environment and will continue returning `false` when running in Node.

Fix incorrect behavior of the isBrowser() function and relative functionality

---

src/GoTrueAdminApi.ts
src/lib/types.ts

Allows you to pass in a `params` object to `listUsers()`; to determine paginated results. 
`listUsers()` will only return the first 50 results.
Introduces an options object to `listUsers()`. The two options are `page` and `per_page`. They can be used together or individually. These option names are consistent with the api code found [here](https://github.com/supabase/gotrue/blob/930f5affdab112db81e17ef799418206bead9092/api/pagination.go#L42-L43).
`page` - which page of paginated results to return
`per_page` - how many results to return per page
Example:
```js
const { data, error } = await client.auth.admin.listUsers({ page: '2', per_page: '100' })
```
`params` option name was based on existing usage like [this](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueAdminApi.ts#L105) …

feat: support pagination options for `listUsers()` method

---

src/GoTrueAdminApi.ts

* Previously, `supabase.auth.admin.mfa.listFactors` was returning the list of factors in this format: 
```
{
data: {
'0': {
id: 'c5355875-9dd0-4aa9-acc8-fd2d00d3fbb8',
created_at: '2022-12-17T01:17:59.379887Z',
updated_at: '2022-12-17T01:17:59.379887Z',
status: 'unverified',
factor_type: 'totp'
}
},
error: null
}
```
but it should actually be:
```
{
data: {
factors: [{
id: 'c5355875-9dd0-4aa9-acc8-fd2d00d3fbb8',
created_at: '2022-12-17T01:17:59.379887Z',
updated_at: '2022-12-17T01:17:59.379887Z',
status: 'unverified',
factor_type: 'totp'
}]
},
error: null
}
```

fix: mfa admin list factors

---

src/GoTrueClient.ts

Adds docs to sign in methods that clarify ambiguous messages when accounts don't exist, email/phone with password combinations are wrong or accounts can only be accessed via social login.

feat: adds docs to clarify account existance hiding messages

---

src/lib/types.ts

Since `getUser()` is being called within `listFactors()`, users shouldn't have to call `getUser()` by themselves to get the most up-to-date information. 
Also `listFactors()` does not seem to be documented in the [js docs](https://supabase.com/docs/reference/javascript/introduction), but should we add it?
Credit goes to @Vinzent03 for noticing these while working adding MFA support to the Flutter SDK 🎉

fix: remove comments about calling `getUser()` in listFactors()

---

src/GoTrueClient.ts

Uses [`window.location.replace()`]() instead of setting the `window.location.hash = ''` to ensure that the implicit flow URL is popped from the back stack and can't be navigated to.
Does not use the `history.replaceState()` API since this fragment is not a history-style fragment.
Fixes: #302.

feat: pop implicit flow URL from back stack

---

src/GoTrueClient.ts

[`location.assign()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign) has the same semantics as [`location.href = ...`](https://developer.mozilla.org/en-US/docs/Web/API/Location/href) but it's easier to stub out for integration tests and other things.
Fixes: #155

fix: use `location.assign()` instead of `location.href`

---

src/GoTrueAdminApi.ts

* Adds the option for soft deletion for the admin delete user method
* Defaults to hard deletion for backward compatibility reasons

fix: add soft delete option in deleteUser

---

src/lib/helpers.ts

Better compatibility with mobile applications.
The function only works in browser or node environments. React Native folks can work around this by installing a third-party module; but I've been told these don't work with Expo, although I've not verified.
The function decodes the JWT payload with native javascript; and no longer relies on atob, buffer, or a third-party module.
99% of the code was created by ChatGPT. I tweaked some variable names and had to add an additional check in a couple of spots.
Has been tested against two JWTs from the interwebs and the test suite.
Closes https://github.com/supabase/supabase/issues/11382
Possibly takes care of https://github.com/supabase/supabase-js/issues/669 as well.

fix: decodeBase64URL compatibility

---

src/GoTrueClient.ts
src/lib/helpers.ts
src/lib/types.ts
test/GoTrueClient.test.ts

Adds a new algorithm that automatically refreshes the user's session.
Problems with the previous algorithm:
- Complex retry logic 
- Difficult to read and reason about quickly
- Used in-memory state while session state is not in memory -- local storage, cookies, etc.
- Could produce endless retries
- Not multi-tab resilient -- performed refresh from all open tabs at once
- Not clock-skew resilient
New algorithm:
- Runs every 10 seconds (`AUTO_REFRESH_TICK_DURATION`) -- tick
- Each tick checks the session from the proper storage medium (not possible to have unsynced state)
- If the expiration is within 3 ticks (`AUTO_REFRESH_TICK_THRESHOLD`) a refresh is attempted
- If a refresh is not successful, another one will be attempted on the next tick
- A failing refresh due to network errors will …

feat: add new auto refresh token algorithm

---

src/GoTrueClient.ts

In #564 `setInterval` started being used, however the existence of this type of object marks a NodeJS process as never finished which makes tests hang. By calling [`Timeout#unref()`](https://nodejs.org/api/timers.html#timeoutunref) the interval will continue to run but not hang the process.
Fixes #597.

fix: use `unref` on `setInterval` to stop tests from hanging

---

src/GoTrueClient.ts
src/lib/helpers.ts

Uses the [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) API to register a new broadcast channel (using the `storageKey` option as the channel's name) which will broadcast state change events from the originating tab to all other open tabs.
This is only available when a browser environment is detected _and session persistence is enabled._ Environments that are not browsers or browsers without session persistence are not able to use this feature since they have no way of synchronizing the underlying session storage.

feat: add multi-tab state change notifications

---

src/lib/types.ts
test/lib/utils.ts

* Remove the `data` property from the `AdminUserAttributes` type since it's unused

fix: remove data property from AdminUserAttributes

---

src/GoTrueClient.ts
src/lib/types.ts

The data param to [signInWithPassword](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L326) ?
seems to be [not used in GoTrue](
https://github.com/supabase/gotrue/blob/master/internal/api/token.go#LL58C34-L58C34)

Remove unused data field on signInWithPassword

---

src/lib/types.ts

Since we have move `updateUser` to the public namespace, non-service role keys can now modify `auth.users.metadata`
Aims to address [docs issue](https://github.com/supabase/supabase/issues/10058)

docs: update user metadata to be modifiable

---

src/GoTrueClient.ts

* Attempts to fix #518 , #615 
* During the instantiation of `GoTrueClient`, the constructor notifies all subscribers if it detects that there is an existing session. In some situations, `onAuthStateChange` is called much later in the callstack which results in the constructor notifying an empty list of subscribers before `onAuthStateChange` is able to add any subscribers. 
* By wrapping the notifications in a `setTimeout(() => ..., 0)`, we are able to push the `notifyAllSubscribers` function into the event loop and prioritise running `onAuthStateChange` first. 
* Because I couldn't reproduce the problem, I had to come up with scenarios which would simulate `onAuthStateChange` being run at a later time. 
1. Simulate a computationally intensive function before `onAuthStateChange` runs …

fix: defer `notifyAllSubscribers` in the constructor

---

src/GoTrueClient.ts
src/lib/types.ts

We wish to add support for the [Whatsapp Programmable Messaging API](https://www.twilio.com/docs/whatsapp/api) for Twilio and possibly for other providers in the near future.
This would allow users to send one time verification codes over Whatsapp instead of SMS which is arguably a more secure channel
Methods affected:
- `supabase.auth.signInWithPassword`
- `supabase.auth.signInWithOTP`
How to test
1. Clone  gotrue-js and checkout `j0/support-whatsapp`
2. Clone gotrue and checkout `j0/support-whatsapp`
3. Go to your app and change dependency to point to point to gotrue-js
```
supabsae.auth.signInWithOtp({ phone: '<your-special-number-with-international-code>', options: {
channel: 'sms'}}))
```
```
supabase.auth.signInWithPassword({
phone: '<your-special-number-with-international-code>', …
```

feat: add support for whatsapp programmable messaging API

---

src/GoTrueClient.ts

`BroadcastChannel` seems to be available but not instantiable in environments such as Figma. This makes it possible to use the library without crashes in such cases.

feat: trap errors when `BroadcastChannel` is not supported

---

src/lib/types.ts

Based on some feedback recently, these properties should have been nullable/optional. Although this is a backward incompatible change, it is likely the codebases needing attention after this change is relatively minor.

feat: make certain properties in `UserIdentity` nullable

---

src/GoTrueClient.ts
src/lib/types.ts

* Run callback when `onAuthStateChange` is first invoked with an `INITIAL_SESSION` event
* Fixes #313

feat: invoke callback on onAuthStateChange

---

src/GoTrueClient.ts

* Only fire either the `PASSWORD_RECOVERY` event or the `SIGNED_IN` event instead of firing both when a password recovery link is clicked
* Mentioned in: https://github.com/supabase/gotrue-js/issues/349

feat: dont fire `SIGNED_IN` event on `PASSWORD_RECOVERY`

---

src/GoTrueClient.ts

change `oauth_pkce` to be just `pkce` so that  magic link, recovery, etc can make use of the same route
Upd: realized that there's still a need to encode what kind of flow resulted in the token in order for `issueRefreshToken` to track where the token came from

refactor: drop oauth_

---

src/lib/types.ts

* Update the types to include `email` as a verification type
* Related gotrue PR: https://github.com/supabase/gotrue/pull/885

fix: add email as a verification type

---

src/GoTrueClient.ts

feat: use `Deno.unrefTimer` to stop runtime from hanging

---

src/GoTrueClient.ts

Reverts supabase/gotrue-js#632

feat: revert use `Deno.unrefTimer` to stop runtime from hanging

---

src/lib/helpers.ts

We drop the window prefix so that crypto can also draw from `globalThis` when in a node js environment

feat: drop window prefix

---

src/GoTrueClient.ts

* `signOut` method should remove any unused code verifier from local storage

fix: signOut should remove any unused code verifier

---

src/GoTrueClient.ts
src/lib/helpers.ts

* This PR improves support for using PKCE in environments where the crypto API is undefined (e.g. Node18 in NextJS server-side) 
* If the crypto API is undefined, gotrue-js will default to using `plain` instead `sha256` for the code challenge method

fix: default to plain code challenge method if crypto API is undefined

---

src/GoTrueClient.ts

It appears that for unknown reasons the `/token` endpoint in GoTrue may last significantly longer than 10 seconds. This would mean that a repeat request could be sent out while the first one has not finished.
Longer request times than 30 seconds are generally not possible on the modern web, as many CDNs and proxies default time-out responses to 30 seconds.

feat: increase auto refresh tick duration to 30s from 10s

---

src/GoTrueClient.ts

Currently, the doc string states that it logs in a user via a third party provider. This is a relic from when it was only used for `signInWithOAuth`. The docstring has since been updated

docs: correct docstring on exchangeCodeForSession

---

src/GoTrueClient.ts

We remove the `code` parameter  after exchanging  the code for session if user has `detectSessionInURL` enabled

feat: remove code param

---

src/lib/types.ts

Bug fix
Zoom is not mentioned among the other providers in /src/lib/types.ts file
Doc: https://supabase.com/docs/guides/auth/social-login/auth-zoom#add-login-code-to-your-client-app
`signInWithOAuth` doesn't throw type error
```
async function signInWithZoom() {
const { data, error } = await supabase.auth.signInWithOAuth({
provider: 'zoom',
})
}
```
Issue:  https://github.com/supabase/gotrue-js/issues/675

Added missing zoom provider in types.ts

---

src/GoTrueClient.ts

If a client is constructed when the underlying access token has expired and auto refresh is disabled, the session is getting removed. It should not be removed as the session can be automatically refreshed either with the auto refresh mechanism or whenever `getSession` is called next.

feat: keep expired session on initialization

---

src/GoTrueClient.ts
src/lib/types.ts

* Supercedes #258
* Adds `reauthenticate()` method to allow a user to request for a nonce to subsequently update their password
* Updates the type for `UserAttributes` which is used in `updateUser()` to include the `nonce` 
* If a nonce is not passed into `updateUser()`, an `AuthSessionMissingError()` will be returned
With this addition, the update password flow will look like the following when "Secure password change" is enabled on the Supabase dashboard. For users that are self-hosting gotrue and using gotrue-js, this requires setting the environmentr variable, `GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION="true"`
```
// Send reauthentication to the current user. User must be signed-in to perform this action.
await supabase.auth.reauthenticate()
// Update password 
await …
```

fix: add reauthenticate method

---

src/GoTrueClient.ts

* Attempts to clear up the confusion in #539 due to unexpected behaviour when no storage option is provided and `persistSession: true`.

fix: return warning if `persistSession` is true with no storage option

---

src/GoTrueClient.ts
src/lib/errors.ts
src/lib/types.ts

Currently, the `AuthReponse` allows for the possibility of an [empty Session, empty User and no error](https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L56). This might not be ideal for users who might expect an error when no `User` or `Session` is returned.  This PR aims to eliminate this possibility via a more specific type which covers all token related endpoints.
We introduce a generic `AuthTokenResponse` to cover the case where there is no Session and no User but no error. In practice, this hopefully won't happen. Not too familiar with the typings so do feel free to lmk if there's anything I've missed or if there are alternative solutions.
Context: Aims to address #686.

refactor: update types for /token linked methods

---

src/GoTrueClient.ts

Aims to address #700
We move the location of the `isBrowser()` check so that  Server side clients don't have to perform the check repeatedly.  Also changes the ordering of a condition to allow short circuit evaluation

feat: change location of evaluation

---

src/GoTrueClient.ts
src/lib/errors.ts

If the `_callRefreshToken` method failed with a network error, the session would have been removed, which should generally not be the case as the device is offline.

feat: `_recoverAndRefresh` does not remove session on retryable error

---

src/lib/fetch.ts

`_handleRequest` used a Promise instead of async/await which made traces difficult to debug. Additionally, it handles direct fetch errors which are always indicative of a network error, CORS or other such issues and propagtes the error directly.

feat: refactor `_handleRequest`

---

src/GoTrueClient.ts

In `_recoverAndRefresh()` if the session was valid and not expired by the margin, it was loading and then persisting which could have overridden a new session value saved by another tab in local storage.
This explains some errors where a refresh token is used again after a long time.

feat: no persist of session with no changes in `_recoverAndRefresh`

---

src/GoTrueClient.ts

Auto refresh should be attempted when the threshold is reached, not after it is reached.

feat: use `<=` for auto refresh token threshold

---

src/GoTrueClient.ts
src/lib/types.ts

Updates the `signInWithIdToken` API:
- No longer experimental.
- Adds optional `access_token` parameter.
- Updates the types on `provider`.
- More docs.
To be merged after release of: https://github.com/supabase/gotrue/pull/1108

feat: complete OIDC support for Apple, Google and others

---

src/lib/types.ts

This PR adds 'kakao' to `Provider` type.
Kakao provider was recently added to `supabase/gotrue` through this [PR](https://github.com/supabase/gotrue/pull/834)(document has also been updated. [PR](https://github.com/supabase/supabase/pull/14287)) 
IDE warns type error because there is no 'kakao' in `Provider` type.
'kakao' added properly in `Provider` type, so no error shown in IDE
Please let me know if I have to change anything to be approved. Thank you!

feat: Add 'kakao' to Provider type

---

src/GoTrueClient.ts
src/lib/types.ts

* Adds the `emailRedirectTo` option to resend method
* Resolves https://github.com/supabase/gotrue/issues/1142

fix: add emailRedirectTo option to resend method

---

src/GoTrueClient.ts

Bug fix
When you call the `resend` method to e.g. resend an email to change your email, you get logged out.
On email and phone change you don't get logged out.
I noticed this when implementing this method in gotrue-dart https://github.com/supabase/supabase-flutter/pull/517#discussion_r1246427921

fix: don't remove session in resend

---

tsconfig.json

Sets the TypeScript compile target to ES2017 as ES2015 is now 8 years old. Furthermore, ES2017 targets do not transpile async/await to JS generators, which means that stack traces will now be readable.

feat: bump typescript target to ES2017

---

src/GoTrueClient.ts
src/index.ts
src/lib/locks.ts
src/lib/types.ts

Built on top of: #734 
Adds an experimental `lock` option. This is used internally within `_acquireLock()` which can be used to acquire a global exclusive lock when using the client. It can prevent issues with concurrent access to local storage.
`navigatorLock` is an experimental lock that can be used to test the library before officially designating it (or an alternative) as the default global exclusive locking mechanism. It will be rolled out on supabase.com/dashboard over time as we grow our confidence in the library.

feat: add _acquireLock and navigatorLock

---

src/GoTrueClient.ts
src/lib/types.ts

* Allows passing a `token_hash` and `type` in `verifyOtp` method 
* Supports this change on gotrue: https://github.com/supabase/gotrue/pull/1165
* Fixes #694

fix: add verify token hash

---

src/GoTrueClient.ts

Previously `__loadSession` didn't wait for initialization to finish _if stack guards were not supported_ which broke some flows.
This fix attempts to identify recursive calls to `_initialize`, i.e. recursive waiting for `inititalizePromise`:
1. When the session is detected from URL, `GoTrueClient` needs to call `getUser(accessTokenFromURL)` to fetch the user. But this then depended on `_useSession`, which calls `__loadSession` which waits for `initializePromise`. With this PR, it no longer calls `_useSession` if the access token is provided.
2. `_onVisibilityChanged` could be called from within `#_initialize` which would block. Now it's called with a `setTimeout` of 0 so the processing takes place in the next event loop pass.
3. `_startAutoRefresh` which calls `_onAutoRefreshTokenTick` …

fix: always wait for `_initialize` before loading the session

---

src/lib/locks.ts

Bug fix
If using Supabase auth in a Deno application, running a `deno compile`'d executable would not be possible as the `internals.debug` property was still trying to access localStorage [which Deno can't do with an executable](https://deno.land/manual@v1.36.0/tools/compiler#unavailable-in-executables)
Fixes #752
Adds a simple check that is used elsewhere to check if localStorage *really* is able to be used

fix: better defined localStorage support for debug

---

src/GoTrueClient.ts
src/lib/locks.ts

Similarly to how the refresh token ticker needs to acquire the lock before checking whether the session needs to be refreshed, we need to do the same for the visibility change callback. This is difficult to spot because when one uses tabs instead of windows, there's often just one tab visible at once. But when using multiple windows, a window is not hidden when not focused, so events like waking from sleep will cause all windows to refresh the token at once. Adding the lock will serialize access, meaning that all windows will check the session, but only one will refresh.

feat: acquire lock around visibility change callback

---

src/GoTrueClient.ts
src/lib/locks.ts

It looks like there are some instances where Chrome returns a `null` lock object from [Navigator LockManager request](https://developer.mozilla.org/en-US/docs/Web/API/LockManager/request) even though this should only be the case if `ifAvailable` is set to `true`. This change logs a warning.

feat: `navigatorLock` check for spec compatibility

---

src/GoTrueClient.ts
src/lib/fetch.ts
src/lib/helpers.ts

Related to: https://github.com/supabase/gotrue/pull/1183
Built on top of: #733 
Parses `expires_at` from the URL or request if present. Emits warnings if clock skew issues are detected.

feat: parse `expires_at` if present

---

src/GoTrueClient.ts
src/lib/types.ts

Allows customizing the debug log function (which is `console.log` by default) to support complex logging scenarios such as writing the logs to IndexedDB or sending them to a server or other monitoring software.

feat: allow customizing the debug log function

---

src/lib/types.ts

* Exposes the `role` field in the admin user type

fix: expose role in admin user type

---

src/lib/helpers.ts

This PR fixes an issue where gotrue would throw in React Native due to the lack of the crypto and TextEncoder module.
When [integrating Segment with React Native](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/), they ask you to install [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values) as a polyfill to crypto's `getRandomValue` method. This causes issues in gotrue, as the code does a simple `crypto !== undefined` check.
Since a lot of RN libraries polyfill only a subset of crypto's method, `crypto !== undefined` is not a bullet-proof way to check for support.
If you have Segment installed, and try to login with `supabase.auth.signInWithOtp` (email), the app throws an error.
If the required crypto modules are not …

feat: pkce challenge support in React Native with Segment

---

src/GoTrueClient.ts

Currently, `PASSWORD_RECOVERY` auth event is not emitted during a password recovery flow using pkce. 
Calling `resetPasswordForEmail()` method 
Calling `resetPasswordForEmail()` sets a code verifier and the auth flow `PASSWORD_RECOVERY` with a `/` separator on the local storage like this: 
`${codeVerifier}/PASSWORD_RECOVERY`
Within `_exchangeCodeForSession()`, the auth flow and the code verifier is extracted from local storage, and if the auth flow is `PASSWORD_RECOVERY`, then `PASSWORD_RECOVERY` event is fired instead of `SIGNED_IN` event.

fix: add password recoery flow support for pkce

---

src/lib/errors.ts
src/lib/fetch.ts
src/lib/helpers.ts

Throws an `AuthWeakPasswordError` on non-200 JSON reponses that have the `weak_password` property as defined in:
- https://github.com/supabase/gotrue/blob/master/internal/api/password.go
- https://github.com/supabase/gotrue/blob/master/internal/api/errors.go#L244

feat: add `AuthWeakPasswordError`

---

example/react/src/App.js
src/GoTrueClient.ts
src/lib/helpers.ts
src/lib/types.ts

* Adds 3 new methods: `unlinkIdentity`, `linkIdentity`, `getUserIdentities` to support the new identity linking endpoints
* All methods require the user to be authenticated 
* This PR should only be merged once the gotrue release with the new identity linking endpoints are deployed

feat: add identity linking methods

---

src/GoTrueClient.ts

docs: fix tsdocs format

---

src/lib/fetch.ts

Made an oops by calling reduce on an object, not an array.

fix: weak password error runtime type checks

---

.github/workflows/release.yml
README.md
example/react/package-lock.json
example/react/package.json
example/react/src/App.js
infra/docker-compose.yml
package-lock.json
package.json
src/AuthAdminApi.ts
src/AuthClient.ts
src/index.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

Renames GoTrue to Auth.
`GoTrueClient` and `GoTrueAdminApi` still remain the main classes, but they're re-exported as `AuthClient` and `AuthAdminApi`.

rename: `gotrue` to `auth`

---

.github/workflows/release.yml

Specifies the repository URL config so `semantic-release` will work: https://semantic-release.gitbook.io/semantic-release/usage/configuration#repositoryurl

ci: fix release workflow after rename

---

.github/workflows/release.yml

The stupid macOS incompatible `sed -i ''` option broke it.

ci: fix sed for releasing `@supabase/gotrue-js`

---

src/GoTrueClient.ts

Currently when code exchange for pkce flow is triggered on device that didn't start the auth flow (e.g. signed up via magic link on laptop and clicked on the link on phone), `TypeError: Cannot read properties of null (reading 'split')` error is thrown. This PR fixes that.
Fixes the error pointed out here
https://github.com/supabase/gotrue-js/pull/813#discussion_r1428876014

fix: Type error on code exchange when no item in storage

---

package.json

Makes sure that `npm publish` runs in public mode always. https://stackoverflow.com/questions/41981686/getting-error-402-while-publishing-package-using-npm

package: set private to false

---

.github/workflows/release.yml

`npm publish` is required instead of `npx semantic-release` because the semantic release has previously run for `@supabase/auth-js`. This just publishes the package under a different name.

ci: publish @supabase/gotrue-js

---

src/GoTrueClient.ts
src/lib/locks.ts

After having spent months of real-world testing on supabase.com, the `navigatorLock` is enabled on browsers that support the [Navigator LocksManager API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API).
This makes sure that concurrent access to the storage in multiple tabs, windows or promises is no longer possible, thus removing issues such as:
- Refreshing the session in parallel
- Saving inconsistent state to storage

feat: default to `navigatorLock` on browsers

---

.github/workflows/release.yml

If the previous step with `npx semantic-release` needs to publish a version, it will update the `package.json` file with the correct version. Only then should `@supabase/gotrue-js` be published.

ci: only publish @supabase/gotrue-js if version is not 0.0.0

---

src/GoTrueClient.ts

Bug fix
Currently when the user goes through the password recovery flow via OTP and calls the `verifyOtp()` method, the `SIGNED_IN` auth event is emitted instead of `PASSWORD_RECOVERY` event. 
When the user goes through the password recovery flow using email OTP, the `PASSWORD_RECOVERY` event is emitted. 
A Flutter SDK user reported this, and thought it probably makes sense to bring it to the JS client as well. https://github.com/supabase/supabase-flutter/pull/774

fix: Emit password recovery event from verifyOtp when otp type is recovery

---

.github/workflows/docs.yml
.github/workflows/release.yml

We move from node 18 to 20 mirroring changes across the org
It is also required for [the latest sem release which is used in the build](https://github.com/supabase/gotrue-js/actions/runs/7580380386/job/20646093342#step:5:10)

fix: upgrade to node 20

---

src/lib/types.ts

We introduced friendly name in the response of `enroll` a while back: https://github.com/supabase/gotrue/pull/1277
This PR adds the field to the client library response

chore: add friendly name to enroll response

---

.github/workflows/manual-publish.yml

Adds an option to manually publish a tag on NPM in case the release CI job has bugs or has failed to publish the correct artifact on NPM.

ci: add manual package publish on git tag

---

.github/workflows/manual-publish.yml

`inputs` instead of `input`. 🤦

ci: fix typo in manual-publish workflow

---

src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueClient.test.ts

Warn about using `getSession()` when the storage has `isSever` to true without previously having called `getUser()`.
Warn each time the `user` is accessed as returned by `getSession()`.
Relates to:
- https://github.com/supabase/auth-helpers/pull/722

feat: warn use of `getSession()` when `isServer` on storage

---

src/lib/fetch.ts

Next.js polyfills the `fetch` on the server side to always cache (what's known as their Data Cache) responses. Quote:
> Next.js has a built-in Data Cache that persists the result of data fetches across incoming server requests and deployments. This is possible because Next.js extends the native fetch API to allow each request on the server to set its own persistent caching semantics.
>
>  Good to know: In the browser, the cache option of fetch indicates how a request will interact with the browser's HTTP cache, in Next.js, the cache option indicates how a server-side request will interact with the server's Data Cache.
This is _incredibly dangerous_ for Auth use cases. Thankfully, it appears that using the default client uses `@supabase/node-fetch` in such a circumstance which should not …

feat: explicit `cache: no-store` in fetch

---

.github/workflows/conventional-commits-lint.js
.github/workflows/conventional-commits.yml

Adds a linter for commits and PRs to ensure that correct structure is observed. Certain directives are not compatible with this project:
- Breaking changes are not allowed. Therefore PR titles or commit messages must not use the `!` nor the `BREAKING CHANGE` directive in descriptions or commit messages.
- The `Release-As` directive is not supported as it can break the release process.
- For cleanliness, only a few conventional commit prefixes are allowed.
These are linted using a simple JavaScript script that runs on PRs and pushes.
Similar to:
- https://github.com/supabase/gotrue/pull/1392

ci: add conventional commits linter

---

example/react/package.json
example/react/src/App.js
src/GoTrueClient.ts
src/lib/types.ts

* https://github.com/supabase/gotrue/issues/68
* Adds the `signInAnonymously` method to support https://github.com/supabase/gotrue/pull/1460
* Passing in user metadata / the captcha token in `signInAnonymously` looks like: 
`signInAnonymously({ options: { data, captchaToken }})` 
which follows the same format as the other sign up / sign in methods

feat: add method for anonymous sign-in

---

src/lib/types.ts

Types update
User type is missing 'is_anonymous' property.
User type has the 'is_anonymous' property.
I'm not 100% certain if this property is optional or not, hoping @kangmingtay can offer some insight as they implemented the feature in https://github.com/supabase/auth/issues/68
Fixes https://github.com/supabase/auth-js/issues/872

chore: add missing 'is_anonymous' property to User type

---

src/GoTrueClient.ts

If there is no session (i.e. no JWT/access token), `getUser()` cannot possibly work. It now returns null user.
Previously, it just sent out a request _without the JWT_. When combined with `@supabase/supabase-js` which does some clever tricks with `fetch` by adding a default `Authorization` header using the Supabase `anon` API key, if you called `getUser()` at the wrong time an error such as `missing sub claim` error message would be thrown by Supabase Auth.
(Unfortunately the Supabase `anon` API key is signed with the same JWT secret, so it's hard to disambiguate why this is happening.)

fix: `getUser` returns null if there is no session

---

src/GoTrueClient.ts

Currently the retry interval of `_refreshAccessToken` goes 200, 400, 600, 800, where as I believe the intended intervals are 200, 400, 800, 1600...
The retry interval is multiple of 200 ms.
The retry interval is properly set exponentially.

fix: implement exponential back off on the retries of `_refreshAccessToken` method

---

.eslintrc.json
src/GoTrueClient.ts
test/GoTrueClient.test.ts

* removes the warning from being logged everytime `getSession` is called
* only log the warning if the user property is being accessed from the session
* addresses #873, https://github.com/supabase/supabase-js/issues/1010

fix: update session warning

---

src/GoTrueClient.ts

* Fixes #881 
* https://github.com/supabase/auth-js/pull/876 introduced a breaking change in `getUser()` which resulted in the authorization header not being used

fix: check for access token in header

---

src/lib/fetch.ts

Fixes https://github.com/supabase/supabase-js/issues/1001
Hopefully the NextJS caching takes in the Authorization header in the cache key.

feat: remove `cache: no-store` as it breaks cloudflare

---

src/GoTrueClient.ts

Reverts supabase/auth-js#882 due to
> One thing to keep in mind is that the Authorization header will always exist since the anon key is there by default, right? So hasAccessToken will always be true; which makes this whole section of code useless, and you might as well go back to no checks.
>
> One thing you could do when the client is created is check if the dev passed in an Authorization header. If so, set something like this.hasCustomAuthHeader = true - which would be intialized as false during client creation.
> 
> Then you could check for that on the right side of || in this getUser code.

fix: revert check for access token in header

---

src/GoTrueClient.ts

This reverts commit 6adf8caa4ca803e65f943cc88a2849f5905a044a.
Revert check for access token before fetching user. While potentially beneficial, we'll need to update our guides and address a few other issues before we can proceed with this change

fix: Revert "fix: `getUser` returns null if there is no session (#876)"

---

src/GoTrueClient.ts
src/lib/types.ts

* Adds a new property `hasCustomAuthorizationHeader` which will be set by supabase-js 
* `getUser` should return an `AuthSessionMissingError` if there is no session and no custom auth header is set

fix: return error if missing session or missing custom auth header

---

infra/docker-compose.yml
src/GoTrueClient.ts
test/GoTrueApi.test.ts
test/GoTrueClient.test.ts

* fixes https://github.com/supabase/auth/issues/1550 and https://github.com/supabase/auth/issues/1518
* update tests to use latest auth version

fix: signOut should ignore 403s

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

* we can safely suppress the warning returned by `_getSession` whenever `_saveSession` is called - this further reduces the noise in #874

fix: suppress getSession warning whenever _saveSession is called

---

.github/workflows/ci.yml

* update `actions/checkout` and `actions/setup-node` to v4

ci: upgrade actions to v4

---

infra/docker-compose.yml

* bump the auth image used in tests to the latest version

chore: bump auth version in test

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

Bug fix.
A call to `getSession()`, when using server storage, logs a warning every time `session.user` is accessed. This is causing a lot of people to see multiple consecutive logs to the console - especially for SvelteKit users.
Ensures that accessing `session.user`, from a `getSession()` call, only logs the warning once per Proxy session instance. In other words, once per server request.
https://github.com/supabase/auth-js/issues/888

fix: limit proxy session warning to once per client instance

---

src/GoTrueClient.ts
test/GoTrueClient.test.ts

* Replaces #854 
* Fixes #853, #904 
* We don't need to remove the existing session prematurely. This causes some issues when users want to implement some sort of switch-account functionality since the existing session will always be removed regardless of whether the signup / sign-in attempt succeeds. 
* It's safe to remove `_removeSession` since calling `_saveSession` multiple times will just replace the existing session

fix: don't call removeSession prematurely 

---

.github/workflows/release.yml

See: https://github.com/supabase/ssr/pull/13/files

ci: fix doubling of rc version identifier

---

.github/workflows/release.yml

Fixes: #921  so we add the latest tag on npm.
Currently we [publish the package](https://www.npmjs.com/package/@supabase/auth-js?activeTab=versions) but the tag doesn't seem to be appended correctly

fix: patch release workflow

---

src/GoTrueClient.ts

Bug fix
The variables where having types undefined, but they should have the type string or undefined
Fixed the types for the variables

fix: type errors in verifyOtp

---

src/lib/types.ts

* Adds the `slack_oidc` provider, which supports the slack v2 API
* Adds 2 new fields to the admin create user method - `password_hash` and `id`, which allows one to specify a password hash or a custom id when creating a user through the admin method 

fix: update types 

---

package.json

See announcements: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
`docker-compose` (V1) is no longer in ubuntu-latest 22.04

fix: move docker compose to v2

---

src/GoTrueClient.ts
src/lib/types.ts

Adds the bindings for MFA (Phone) Client library. In particular, add
- Enroll - now allows for enrollment of Phone Factors
- Challenge for Phone - now takes in a channel
- List Factors - now supports access of Phone factors
- `challengeAndVerify` will currently return an error on the `verify` step when used with a phone factor. We could introduce an alternate behaviour (e.g. terminating at the `challenge` step gracefully) since we have the `type` of the challenge-associated-factor in the response. This is not addressed in this PR

feat: add bindings for Multi-Factor Authentication (Phone)

---

src/GoTrueClient.ts

This PR corrects the spelling of `clock` in a warning message in `GoTrueClient.ts`.
```
@supabase_supabase-js.js?v=12ace510:5329 @supabase/gotrue-js: Session as retrieved from URL was issued in the future? Check the device clok for skew 
```
```
@supabase_supabase-js.js?v=12ace510:5329 @supabase/gotrue-js: Session as retrieved from URL was issued in the future? Check the device clock for skew 
```

fix: Correct typo in GoTrueClient warning message

---

src/GoTrueClient.ts
src/lib/errors.ts
src/lib/fetch.ts

When the access token (JWT) contains a `session_id` property which does not correspond to a row in the `sessions` table, it means that the user has been signed out or the session has been destroyed in some way. Auth will send back a `session_not_found` error code which can be detected by the client library and removing of the stored session with emitting the `SIGNED_OUT` event should take place.

feat: remove session, emit `SIGNED_OUT` when JWT `session_id` is invalid

---

src/lib/types.ts

Adds the `kakao` string to the supported `signInWithIdToken` types.
Merge after: https://github.com/supabase/gotrue/pull/1381

feat: add kakao to sign in with ID token

---

src/GoTrueClient.ts
src/lib/types.ts
test/GoTrueClient.test.ts

Bug fix for the TypeScript types.
- Fixes https://github.com/supabase/auth-js/issues/955
Use [TypeScript's function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) to return
- TOTP data when `mfa.enroll` was passed `factorType: 'totp'`,
- phone data when `mfa.enroll` was passed `factorType: 'phone'`.
This fixes a breaking change in the types in b957c30782065e4cc421a526c62c101d35c443d4.
This PR would also expose the new following types:
- `MFAEnrollTOTPParams`
- `MFAEnrollPhoneParams`
- `AuthMFAEnrollTOTPResponse`
- `AuthMFAEnrollPhoneResponse`
- `AuthMFAEnrollErrorResponse` (it might be better to roll this type in with the other two).
It might be better to keep these types private, since once they're exposed, you can't easily remove them …

fix: improve `mfa.enroll` return types

---

src/GoTrueClient.ts

Addresses a few existing TODOs
- Remove the deletion of  TOTP object for backward compatibility
- Matches on identity linking error codes instead of messages

fix: remove phone mfa deletion, match on error codes

---

src/GoTrueClient.ts
src/lib/internal-types.ts
src/lib/types.ts

Follow up to #956, hides the MFA sub-types (e.g. MFA Phone, MFA TOTP) needed to fix type errors before we release to public so that we can remove them as and when we like. The sub-types are now stored in an `internal-types` file which, unlike the `types` file is not exposed to public.
The types mentioned here have not been released yet so fine to hide them

fix: move MFA sub types to internal file

---

.github/workflows/conventional-commits-lint.js
.github/workflows/conventional-commits.yml

Bug fix
Some github.event messages can break the workflow. Backticks get interpreted by the shell, this is a security risk and also breaks most Dependabot PRs.
Updates the workflow to deal with special characters that might be interpreted by the shell
Should fix https://github.com/supabase/auth-js/actions/runs/11035778554/job/30652617566

chore: update workflow check-conventional-commits

---

src/GoTrueAdminApi.ts

For clarity as it seems to be confusing users.  Ticket linked internally.

fix: update soft-deletion docs

---

src/GoTrueClient.ts

Fix a small typo in the warning message when using user object from the server.

fix: typo in warning message

---

src/lib/locks.ts
test/lib/locks.test.ts

When using the library in non-browser environments like React Native or other JavaScript-based runtimes (Electron's main process for example) certain race conditions could still occur.
We've received some signal from customers using React Native that at scale these become more visible. This is why I'm introducing a `processLock` that developers can import like so:
```typescript
import { processLock } from '@supabase/auth-js/lib/locks'
```
And add to their apps by specifying the lock option with the process lock.

feat: add process lock for optional use in non-browser environments (React Native)

---

src/lib/errors.ts
src/lib/types.ts

Add "loose autocomplete" to`WeakPasswordReasons`, `AMREntry.method`, `Factor.factor_type`, `SignInWithIdTokenCredentials.provider` and `AuthError.code `
The above types define possible string literal values, which is great, but they're unioned with `string`. As a regular `"literal" | string` just ends up as a `string` this foregoes the benefit of defining the literals in the first place. 
TypeScript still allows any possible string as a valid value (notice no error on the "not in there"), but now the predefined literals show up as hints. This is done by using `"literal" | string & {}`. While this seems hacky, it's something that works and something the TS team test against meaning they won't "fix" it in future releases. 
Currently these hints aren't shown as the type just ends up as a …

fix: add loose auto complete to string literals where applicable

---

src/GoTrueClient.ts
src/lib/errors.ts
src/lib/locks.ts

* Don't remove session for identity linking errors
* Dependent on https://github.com/supabase/auth/pull/1855

fix: don't remove session for identity linking errors

---

src/lib/locks.ts

Wraps the `navigator.locks.request()` function with a plain Promise as libraries such as zone.js patch this object to track execution context. It appears that this browser API uses a native promise that's not patched, causing the tracking context to be lost.
It is believed that wrapping this non-zone.js Promise returned by the browser with a promise that's patched by zone.js can help the situation.
Related:
- https://github.com/supabase/supabase-js/issues/936
- #830

feat: wrap navigator.locks.request with plain promise to help zone.js

---

src/GoTrueClient.ts

* When using the PKCE flow, if there's a redirect error after the callback and a code is not returned, `getSessionFromUrl` ends up returning `Not a valid PKCE flow url.` instead of the actual error

fix: return error early for redirects

---

src/GoTrueClient.ts

* Refactor `_getSessionFromURL`, `_isPKCEFlow` and `_isImplicitGrantFlow` - previously we were parsing the url parameters multiple times which was unnecessary. Now, we parse it once and pass it in as an argument in other functions that need it.
* Makes the code more readable since `getSessionFromURL` should only be called in a browser context and if `detectSessionInURL` is set.

chore(refactor): reduce parsing query params unnecessarily

---

src/lib/helpers.ts

There are several checks in `GoTrueClient.ts` that check `window?.[prop]` after checking `isBrowser()` which throws an error in node environments that have `document` defined but not `window`.
Fixes:
- https://github.com/supabase/supabase-js/issues/786

fix: `isBrowser()` to include check on `window`

---

src/GoTrueClient.ts

* Fixes the bug introduced previously in https://github.com/supabase/auth-js/pull/993/files#diff-3522461172efd6058d6b8da62fc2d30d8b524d2b64894ea2c67218c52f7fdff5R310, where it attempted to always try to find a session in the URL, which led to users being logged out on a page refresh
* This PR also reverts the previous PR #992, which returns the error early if there's a redirect, since some redirect errors (like identity linking) should not result in the existing session being removed.
* Tested the following scenarios:
* Sign in and refresh the page
* Sign in and attempt to link an already existing identity
* Sign in and attempt to link a new identity

fix: return redirect errors early 

---

.github/workflows/release.yml
package.json

Will publish `auth-js` and `gotrue-js` with [provenance](https://docs.npmjs.com/generating-provenance-statements).

ci: publish with provenance

---

.github/workflows/dogfooding.yml

Introduces a dogfooding PR check ensuring that the RC version is live on [Supabase Studio](https://github.com/supabase/supabase) before an official version is cut.

ci: add dogfooding check so that RC version is up on supabase/supabase first

---

src/GoTrueClient.ts
src/lib/constants.ts

When `autoRefreshToken` is off (or when a tab is in the background) but `getSession()` is called -- such as in an active Realtime channel, `getSession()` might return a JWT which will expire while the message is travelling over the internet. There is one confirmed case of this happening.
This PR adjusts this using the established `EXPIRY_MARGIN_MS` constant (which only applies on initial initialization of the client). The constant's value is brought in line with the `autoRefreshToken` ticks which run every 30 seconds and refreshing is attempted 3 ticks prior to the session expiring.
This means that JWTs with an expiry value **less than 90s** will always refresh the session; which is acceptable.

feat: consider session expired with margin on getSession() without auto refresh

---

src/GoTrueAdminApi.ts
src/lib/helpers.ts
src/lib/types.ts
test/GoTrueApi.test.ts

You're not supposed to pass non-UUID values for parameters which are meant to be UUID, as well as the sign out scope parameter.

feat: validate uuid and sign out scope parameters to functions

---

src/lib/types.ts

- add missing `deleted_at` property to User interface

fix: add missing `deleted_at` property to `User` interface

---

src/index.ts

Process lock was added in #977 but wasn't exported in top-level which made imports hard.

fix: export `processLock` from toplevel

---

src/GoTrueClient.ts

Due to bad typing the `null` case of a missing session when using the `userStorage` option introduced in #1023 caused a crash.

fix: handle null current session with split session storage

---

src/GoTrueClient.ts
src/lib/constants.ts

`supabase.auth.getClaims()` loses `@expermental` status. To further improve performance since Vercel have now added Fluid Compute which shares a lot more memory between requests, every client's JWKS cache is stored in a global variable under the client's storage key.

feat: make `getClaims()` non experimental, add global cache

---

package-lock.json
package.json
src/lib/solana.ts
src/lib/types.ts

Bundlers are having a hard time with this dependency, and we don't want to directly depend on runtime code from the Solana / Wallet Standard libraries (due to supply chain attacks) so the relevant types are copied over.
Fixes #1076.

feat: remove solana dependency by inlining types

---

src/GoTrueClient.ts
src/lib/helpers.ts

Because the `/.well-known/jwks.json` is heavily cached, a developer may rotate the standby key to in use faster than those caches expire. In that case the `getClaims()` method may receive a JWT signed with a key ID it doesn't recognize. Instead of failing with an error, it should reach out directly to the Auth server to verify the JWT.

feat: fallback to `getUser()` if the `kid` of the JWT is not found

---

src/GoTrueClient.ts
src/lib/helpers.ts

Not all JS runtimes support `structuredClone` (introduced in https://github.com/supabase/auth-js/pull/1023). (Example: https://github.com/supabase/supabase-js/issues/1504) 
- As the session data is safe to JSON serialize, replace `structuredClone` use with JSON de/serialize.
- Added the helper function to increase the readability (making the intent clear).

fix: use JSON-based deep clone instead of structuredClone

---

test/GoTrueClient.browser.test.ts
test/GoTrueClient.test.ts
test/ethereum.test.ts

PR is based on https://github.com/supabase/auth-js/pull/1095. Please, merge the previous one first.
Increased coverage

chore: more tests

---

src/GoTrueClient.ts

Fixes a minor typo in a code comment.
The comment contains a few typos. Please refer to the file changes for details.
The typos in the comment have been corrected. Please refer to the file changes.
This is a minor typo fix in a code comment. No functional changes, so I opened a PR directly without an Issue. Please let me know if you'd prefer a separate Issue as well.

fix: correct typo in GoTrueClient initializePromise comment

---

src/GoTrueClient.ts

Adds `linkIdentity()` method which allows passing OIDC credentials. The ID token will be linked to the currently signed in user.
See also:
- https://github.com/supabase/auth/pull/2108

feat: implement `linkIdentity` for oidc / native sign-in
