package-lock.json, package.json
Bug fix, feature, docs update, ...
=> feat: remove unused packages

example/src/App.js
Add Remember me feature
I have read a few ways to implement the remember me function in several blog pages. Most of these blogs suggest saving username / email to localStorage. Others instruct to install with token but need backend installation so I chose the first option.
closes #6
=> feat: create Remember me feature

package-lock.json, package.json, src/lib/fetch.ts
Migrate to [cross-fetch](https://github.com/lquixada/cross-fetch) from [isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch).
https://github.com/supabase/gotrue-js/issues/12
=> Migrate to cross-fetch

src/GoTrueApi.ts, src/GoTrueClient.ts, test/__snapshots__/client.test.ts.snap, test/__snapshots__/provider.test.ts.snap, test/client.test.ts, test/provider.test.ts, test/subscriptions.test.ts
Rectify tests for Thor's updates
=> Fix tests not passing, add some typings to the API

example/src/App.js, src/GoTrueClient.ts, test/__snapshots__/client.test.ts.snap, test/client.test.ts
Simplifies the `client.user()` and `client.session` methods to return the user|session object or null for better DX
=> fix: Simplify user and session methods.

src/GoTrueApi.ts, src/GoTrueClient.ts, src/lib/fetch.ts
- Applying _early returns_ concept to reduce complexity and refactoring some methods to improve our performance
The only notable change will be improved performance 🚀 
**E.g.:**
- **current:**
`fetch.ts -> get` method complexity is 15
`fetch.ts -> post` method complexity is 14
`fetch.ts -> put` method complexity is 14
---- 
- **new:**
`fetch.ts -> _handleRequest` method complexity will be 12
`fetch.ts -> get` method complexity will be 3
`fetch.ts -> post` method complexity will be 3
`fetch.ts -> put` method complexity will be 3
=> perf: ♻️ applying early returns concept to reduce complexity and refactoring some methods to improve our performance

src/GoTrueClient.ts, src/lib/types.ts
Add a new Type to avoid use duplicated code.
We're duplicating code for lack of specific data type.
Creating this new type, we can remove the duplicated code using the new created type.
=> refactor: add UserCredentials type

RELEASE.md, example/react/src/App.js, infra/docker-compose.yml, src/GoTrueApi.ts, src/GoTrueClient.ts, src/lib/types.ts, test/__snapshots__/provider.test.ts.snap, test/apiWithAutoConfirmDisabled.test.ts, test/provider.test.ts
Will redirect the user after they are confirmed
=> Adds a "redirectTo" option to all relevant functions

src/GoTrueApi.ts
=> fix: #66. Missing redirects on some routes

example/next/package-lock.json, example/react/src/App.js, infra/docker-compose.yml, src/GoTrueApi.ts, src/GoTrueClient.ts, src/lib/helpers.ts, src/lib/types.ts, test/__snapshots__/clientWithAutoConfirmEnabled.test.ts.snap, test/clientWithAutoConfirmEnabled.test.ts
Refactors and fixes:
- Adds a new `expires_at` to the `Session` type
- Adds an sync method to the constructor to (maybe recover the session)
- fix: https://github.com/supabase/gotrue-js/issues/36
- fix: https://github.com/supabase/gotrue-js/issues/52
=> Fix: session refreshing and session recovery

src/GoTrueClient.ts, src/lib/types.ts, test/clientWithAutoConfirmEnabled.test.ts
=> added setSession api

infra/docker-compose.yml, src/GoTrueApi.ts
=> fix: #65 sends redirect in query param instead of referer header

src/lib/types.ts
Adds discord provider to gotrue-js
=> fix: add discord provider

src/GoTrueApi.ts
Noticed this while rewriting gotrue-py. Not sure if it was a typo but decided to file quick PR
Bug fix, feature, docs update, ...
=> Change email address -> phone in documentation

src/lib/constants.ts
fixes: supabase/supabase-js#241
=> fix: require was breaking some builds

package-lock.json, package.json
- closes: https://github.com/supabase/gotrue-js/pull/164
- closes: https://github.com/supabase/gotrue-js/pull/163
- closes: https://github.com/supabase/gotrue-js/pull/162
- closes: https://github.com/supabase/gotrue-js/pull/161
- closes: https://github.com/supabase/gotrue-js/pull/160
- closes: https://github.com/supabase/gotrue-js/pull/159
- closes: https://github.com/supabase/gotrue-js/pull/158
- closes: https://github.com/supabase/gotrue-js/pull/157
=> upgrades jest packages

infra/docker-compose.yml, src/GoTrueApi.ts, src/lib/types.ts, test/clientWithSignupsDisabled.test.ts
- closes: https://github.com/supabase/gotrue-js/pull/115
- blocker: https://github.com/supabase/gotrue/issues/261
=> Feat: create user

src/lib/types.ts
to match https://github.com/supabase/supabase/pull/5018#pullrequestreview-864341046
=> chore: adds notion and alphabetize

src/GoTrueClient.ts
related: 
- https://github.com/supabase/supabase/pull/5999
- https://github.com/supabase/supabase/issues/5663
=> docs: clarify redirect param

src/lib/types.ts
Fix #283
Type error on compilation when using email change related methods
No type errors 🤞 
=> Add new fields on User type

src/lib/helpers.ts
Build fix
Build fails due to no extra semi rule
Ignore the rule where needed
=> fix: ignore no-extra-semi

src/GoTrueApi.ts
* Refactored in gotrue [here](https://github.com/supabase/gotrue/pull/520)
=> fix: rename captcha field

.github/workflows/ci.yml
Seems like we're moving to Node 16 and not 14
=> Bump to Node 16

.github/workflows/docs.yml, .github/workflows/release.yml
Sorry for the many PRs -- realised we need to bump the docs and release node versions too
=> Bump Node(docs + release)

src/GoTrueApi.ts, src/GoTrueClient.ts
* Adds option to pass captchaToken in the signIn methods
=> fix: add captcha config for sign in endpoints

src/GoTrueApi.ts, src/GoTrueClient.ts, src/lib/types.ts
some properties weren't documented since the typedocs were incorrect
=> fix typedocs

src/GoTrueAdminApi.ts, src/GoTrueClient.ts, src/lib/types.ts
* Make the types and definitions pretty
=> fix: cleanup type docs

src/GoTrueAdminApi.ts, src/GoTrueClient.ts, src/lib/types.ts
* Fixes typos / incomplete sentences and unclear documentation
=> docs: update auth docs

src/GoTrueClient.ts, src/lib/types.ts
* Fix issue with `enroll` where the keys are passed in as camelCase instead of snake_case
* Don't capitalise id
=> fix: request body should have keys in snake_case

src/GoTrueClient.ts, src/lib/types.ts
* Returns `provider_refresh_token` if it's present
=> fix: return provider refresh token

src/GoTrueClient.ts, src/lib/helpers.ts, src/lib/types.ts
- Adds the corresponding return type for the /challenge end point, which previously wasn't included
- Introduces `getAMR` and `getAAL` methods
=> Add return type for /challenge and introduces getAAL and getAMR

src/GoTrueClient.ts, src/lib/fetch.ts, src/lib/helpers.ts, src/lib/types.ts, test/GoTrueClient.test.ts, test/fetch.test.ts, tsconfig.json
=> fix: merge rc into mfa

src/GoTrueClient.ts, src/lib/fetch.ts, src/lib/helpers.ts, src/lib/types.ts, test/GoTrueClient.test.ts, test/fetch.test.ts, tsconfig.json
* merged `rc` branch in and resolved the merge conflicts 
* use the `decodeBase64URL` helper function in the `rc` branch
=> refactor: mfa client updates

.gitignore, package.json, src/lib/fetch.ts
* Resolve conflicts with MFA branch
=> chore: resolve merge conflicts with mfa branch

src/GoTrueClient.ts, src/lib/types.ts
Add [`@experimental`](https://tsdoc.org/pages/tags/experimental/) everywhere for MFA.
=> refactor: add experimental typedoc, fix type

src/GoTrueClient.ts
* Fixes missing type import and invalid params passed into `_verify`
=> fix: mfa challenge and verify

src/GoTrueClient.ts
Docs don't support complex types, and it's kinda hard to get that in. Until it becomes possible, we need to be mindful with the types we use as input to functions.
=> refactor: update setSession type (for docs)

src/GoTrueAdminApi.ts, src/GoTrueClient.ts, src/lib/errors.ts, src/lib/fetch.ts, test/GoTrueClient.test.ts
=> fix: signout should remove session if user doesn't exist

src/GoTrueClient.ts, src/lib/types.ts
=> fix: drop experimental MFA tag

src/GoTrueAdminApi.ts, src/GoTrueClient.ts, src/lib/types.ts
=> docs: update tsdocs

src/lib/errors.ts
* Adds the status property to `AuthError` to improve error handling
=> fix: add status property to AuthError

.github/workflows/docs.yml, .github/workflows/release.yml
=> fix: update to node 18

src/GoTrueClient.ts
Reverts supabase/gotrue-js#574.
=> fix: revert pop implicit flow URL from back stack

package-lock.json
=> build(deps): bump json5, minimatch for vulnerabilities

example/react/package-lock.json
`npm audit fix` in `example/react`
=> examples: bump dependencies

example/react/.env.example, example/react/README.md, example/react/src/App.js
Cleanup the example so that you only need to update the .env file instead of copying and pasting code from the README
=> Update example to use .env file

src/lib/types.ts
Bug fix
https://github.com/supabase/gotrue-js/issues/607
=> fix: add missing new_phone property

src/GoTrueClient.ts
* Adds the option to include a redirect url for email change updates
=> fix: add emailRedirectTo option to updateUser

src/GoTrueClient.ts, src/lib/helpers.ts, src/lib/local-storage.ts
=> feat: add enhanced `localStorage` support check

src/GoTrueClient.ts, src/lib/types.ts
Removes the `@experimental` tag from `signInWithSSO` and updates the docs based on feedback.
=> feat: remove experimental from `signInWithSSO`, update docs

src/GoTrueClient.ts, src/lib/helpers.ts
=> refactor: throw errors instead of strings

src/GoTrueClient.ts, src/lib/types.ts
* Fix issue where `_isPKCEFlow` is not being awaited even though it's an async method
* Fix spelling in typedoc
* Remove unused `USER_DELETED` event
=> fix: `_isPKCEFlow` is not being awaited

src/GoTrueClient.ts
Replacement for #654 as the commit history there is a little messy
Corresponding server PR: https://github.com/supabase/gotrue/pull/1027
=> fix: remove oauth flow type

src/GoTrueClient.ts
Replace #652 as the history there seems borked
=> feat: add pkce magic link bindings

src/GoTrueClient.ts
Build errors as Deno is undefined when not using the global runtime.
=> fix: check for Deno

src/GoTrueClient.ts
Adds PKCE bindings for the `signUp` client library method
=> feat: add pkce option to signup

src/GoTrueAdminApi.ts
=> docs: update type docs on `inviteUserByEmail`

src/lib/types.ts
* Fixes an incorrect type in the Resend params
=> fix: update resend types

src/GoTrueClient.ts
* Addresses: https://github.com/supabase/supabase/actions/runs/5087069855/jobs/9142106022?pr=14554
=> docs: fix misspell

src/GoTrueClient.ts
=> feat: update tsdoc

src/GoTrueClient.ts
If a callback passed to `onAuthStateChange` is `async`, the emitter of the event (like `signInXYZ` methods) would wait before returning. All such callbacks will be waited upon to complete, but errors will be reported once all have completed. All such errors are logged, but only the first one is thrown.
Fixes #276
=> feat: add async/await support for `onAuthStateChange` callbacks

src/GoTrueClient.ts, src/lib/types.ts
Adds the ability to configure debug messages for the library, which are useful when inspecting what the GoTrueClient is doing in certain circumstances.
=> feat: add debug messages and configuration

src/lib/types.ts
* Add `figma` provider to the list of Provider types
=> fix: add figma provider

src/GoTrueClient.ts, src/lib/helpers.ts
Safari does not support stack guards as it does not preserve stack traces across async/await calls. This PR removes the reliance on stack guards when they're not supported, but this means that concurrent access can cause random logouts in those browsers.
=> feat: fix stack guard issues with Safari

src/GoTrueClient.ts, src/lib/helpers.ts, test/GoTrueClient.test.ts, test/helpers.test.ts
`_getSessionFromURL` was quite busy by parsing and validating parameters. Refactors it to be hopefully a bit clearer as to what is going on.
=> feat: refactor `_getSessionFromURL` to be easier to read

package-lock.json, package.json, src/lib/helpers.ts, src/lib/locks.ts, test/fetch.test.ts
Part of fixing https://github.com/supabase/supabase-js/issues/612
=> fix: use @supabase/node-fetch

src/GoTrueClient.ts
=> chore: update docs for verifyOTP to include token hash

src/GoTrueClient.ts
Given the changes introduced in #736, some of the MFA methods were exempt from acquiring the lock. However, this appears to have been a bad idea, especially around `_getAuthenticatedAssuranceLevel` which is used while the user is authenticated.
This PR adds the locks in the correct places.
=> feat: acquire locks around mfa methods

src/GoTrueClient.ts
Comment update
A comment with the word jsut instead of just `// we jsut care if it finished`
NA
=> Fix comment typo

src/lib/types.ts
=> feat: add linkedin oidc type

src/GoTrueClient.ts
Companion PR to: https://github.com/supabase/gotrue/pull/1137
Server-Side PR: PKCE https://github.com/supabase/gotrue/pull/1137
=> feat: add SSO PKCE

src/GoTrueClient.ts, src/lib/errors.ts, src/lib/fetch.ts, src/lib/types.ts
Returns the weak password reasons on sign-in.
=> feat: return `weakPassword` information after sign-in

src/GoTrueAdminApi.ts
docs update to provide explanation of soft deletion for delete user endpoint
closes https://github.com/supabase/supabase/issues/20057
Explains what the soft delete flag does so it can be picked up in the Supabase docs
=> Add explanation for soft deletion to user delete function

.github/workflows/release.yml
=> ci: fix release script for gotrue-js

.github/workflows/manual-publish.yml
`toJSON()` doesn't work with `echo`.
=> ci: echo manual-publish inputs

.github/workflows/release.yml
Logs the inputs to the release manual dispatch workflow.
=> ci: log release inputs

src/lib/types.ts
=> fix: remove data type

src/GoTrueClient.ts, src/lib/helpers.ts
Moves all PKCE code generation logic into a single method. This removes duplicate code and facilitates changes around PKCE methods
=> fix: refactor all pkce code into a single method

src/GoTrueClient.ts
* Add tsdocs to the `signInAnonymously` method
=> docs: update tsdocs for signInAnonymously

.github/workflows/ci.yml
Build was missing for some reason. 😱
=> ci: add build step

src/GoTrueClient.ts
* Fixes #782 
* Supercedes #945 
=> fix: don't throw error in exchangeCodeForSession

src/lib/error-codes.ts
* Adds the `email_address_invalid` error code
=> fix: add email_address_invalid error code

src/GoTrueClient.ts
Issues found with previous code: https://github.com/supabase/auth-js/issues/995
=> fix: revert #992 and #993

src/lib/types.ts
As per title - relevant PR: https://github.com/supabase/auth/pull/1768
=> fix: update docs to add scrypt

src/GoTrueClient.ts, src/lib/constants.ts, src/lib/types.ts, test/GoTrueClient.test.ts
* Update `fetchJwk` to refetch the JWKs if the cache is stale
* Add tests for various scenarios
=> fix: set jwks_cached_at

infra/docker-compose.yml, test/GoTrueApi.test.ts, test/GoTrueClient.test.ts, test/lib/clients.ts, test/lib/local-storage.test.ts, test/lib/locks.test.ts
=> chore(tests): added tests

.github/workflows/preview-release.yml
CI/CD enhancement - Improves the preview release workflow and cross-repository testing integration.
- Preview releases are created but there's no automated way to test compatibility with downstream packages
- No cross-repository testing between `auth-js` and `supabase-js`
- Manual testing required to verify changes don't break integration points
- Limited feedback loop for developers on cross-package compatibility
- **Automated Cross-Repo Testing**: Preview releases automatically trigger compatibility tests in `supabase-js`
- **Smart Triggering**: Only runs on actual source code changes (src/, package files, tsconfig) to avoid unnecessary builds
- **Enhanced Control**: Manual workflow dispatch with configurable options for target branch and test triggering
- **Better UX**: PR comments …
=> chore: trigger supabase-js tests

test/GoTrueClient.browser.test.ts, test/GoTrueClient.test.ts
Achiving 80% coverage after this PR
=> chore: added more tests
